name: Build dplay.dll

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSVC x86 environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Compile DLL
        run: |
          rc dplay\dplay.rc
          cl /LD dplay\*.c dplay\*.cpp /link gdi32.lib dciman32.lib user32.lib kernel32.lib uuid.lib winmm.lib advapi32.lib /OUT:dplay.dll /DEF:dplay\dplay.def

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: dplay
          path: |
            dplay.dll
