name: Build DirectPlay DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSVC x86 environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Compile DLL
        run: |
          rc dplay.rc
          cl /LD *.c *.cpp /link kernel32.lib user32.lib gdi32.lib advapi32.lib /OUT:dplay.dll /DEF:dplay.def

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: dplay
          path: |
            dplay.dll
